---
title: Kid's Cup of Rochester
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/kids-cup-website"
url: https://bendrick92.github.io
markdown: kramdown
plugins:
- jekyll-feed
carousel_images:
- "/uploads/golf_balls.jpg"
- "/uploads/golf_cart_1.jpg"
- "/uploads/players_1.jpg"
sponsors:
- image: "/uploads/express_logo.png"
  name: Express Employment Professionals
  link: https://www.expresspros.com/
- image: "/uploads/first_alliance_logo.jpg"
  name: First Alliance Credit Union
  link: https://firstalliancecu.com
