---
title: Kid's Cup of Rochester
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/kids-cup-website"
url: https://bendrick92.github.io
markdown: kramdown
plugins:
- jekyll-feed
next_event:
  date: May 8, 2018
  time: 9:30 - 6:00 PM
  location: Somerby Golf Club
  directions_url: https://www.google.com/maps/dir//''/@44.0477542,-92.6697751,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x87f742b8acef5c79:0xe0c57d3c2c3b35dd!2m2!1d-92.6347557!2d44.0476979
who_we_are:
  content: |
    What began in 1997 as the Miracle Marathon has evolved over the past two decades to the Kid’s Cup Golf Tournament. In the beginning, Mark and Sheryl Tasler simply donated $10,000 to the Miracle Marathon, but with much thought they realized their dollars could go much further.  Rather than donate a lump sum, they began sponsoring the tournament.
    In turn, rather than raise money per hole played, the tournament’s format was changed and golfers began fundraising.  With this transition, the Tasler’s saw their $10,000 donation grow more than tenfold.
    Guided by a small group of volunteers, the tournament is on its 22nd year, and has raised over $1.5 million.  Initially benefitting Mayo Clinic Children’s Center and Gillette Children’s Hospital, in 2012 Kid’s Cup decided all proceeds should stay local and has since benefitted Mayo Clinic and Prenatal and Infant Care at Olmsted Medical Center.  Now, when we say “benefitting” we mean 100% of the money raised go directly to these two organizations.
    How can that be you wonder?  The Kid’s Cup Golf Tournament is funded by the owners of our local [Express Employment Professionals](http://www.expresspros.com) which includes green fees, carts, gifts for the golfers, breakfast, and dinner. In addition, many local businesses step forward with generous donations and volunteers.
  image: "/uploads/players_1.jpg"
sponsors:
- image: "/uploads/express_logo.png"
  name: Express Employment Professionals
  link: https://www.expresspros.com/
- image: "/uploads/first_alliance_logo.jpg"
  name: First Alliance Credit Union
  link: https://firstalliancecu.com
